### ISSUE TITLE
Cannot declare class X, because the name is already in use

### ISSUE THREAD

**Issue by hsmfawaz** [spatie/laravel-settings#117]
Hello **Spatie team**,
When creating a new setting migration with **snake case** like the following 
```bash
php artisan make:settings-migration add_header_details_to_general_settings
```
It will throw an exception
```Cannot declare class add_header_details_to_general_settings, because the name is already in use```

**Comment by rubenvanassche** [comment]
Take a look at the `database/settings` directory of your application, there should already be a class with the same name `add_header_details_to_general_settings`. That's why you cannot add a second one. If you give it another name like `add_header_details_to_general_settings_2` it should probably work.

**Comment by ahmedgadit** [comment]
@rubenvanassche 

recieving same error tried clearing cache, composer dump-autoload

Attaching a screenshot 

![image](https://user-images.githubusercontent.com/40518641/162709417-b98de647-7fe2-450e-8afd-58ee9a750ff4.png)

**Comment by mohssineAboutaj** [comment]
i still get that error 
tried `php artisan cache:clear` and `composer dump-autoload` nothing changed
any help?

**Comment by rubenvanassche** [comment]
Could you check if you have another class named `add tracking api key` within your project?
