### ISSUE TITLE
Hierarchy on setting

### ISSUE THREAD

**Issue by suabahasa** [spatie/laravel-settings#6]
Hi,
Thanks for great library.
Is it possible to define hierarchy on setting's group or property?

**Comment by rubenvanassche** [comment]
There's a Cast for the Spatie [data-transfer-object](https://github.com/spatie/data-transfer-object) package: https://github.com/spatie/laravel-settings/blob/master/src/SettingsCasts/DtoCast.php

You could create a DTO like this:

```php
class PostData extends DataTransferObject
{
    public string $title;
    
    public string $body;
}
```

And create a settings class like this:

```php
class GeneralSettings extends Settings
{
    public PostData $post_data;
    
    public static function group(): string
    {
        return 'general';
    }
}
```

Normally the DTO cast is globally registered so, that's it! Otherwise you have to check your configuration file.
